### ISSUE TITLE
How to set the border in dotted line like that in sample picture?

### ISSUE THREAD

**Issue by Akemi-Homura** [greymd/tmux-xpanes#102]
![image](https://user-images.githubusercontent.com/16780053/43958481-324fdb42-9cde-11e8-9ab4-7e53fe96b00d.png)

**Comment by greymd** [comment]
Use `-t` option.
You need tmux version >= 2.3 also.

**Comment by greymd** [comment]
This border is not given by feature of tmux-xpanes.
Use external patch.
Apply the [patch](https://github.com/silenvx/PKGBUILD/blob/master/tmux/borders.patch) to the tmux source code and build tmux manually.

Due to Japanese localized character spacing, the layout of the panes would be broken in my environment. That's why I am usually using this doted border like this to test tmux-xpanes.

FYI, here is my dockerfile which installs tmux with this patch.
https://github.com/greymd/dockerfiles/blob/master/dev/ubuntu/Dockerfile#L111
