### ISSUE TITLE
xpanes:Warning: 'xpanes' may not work correctly! Please check followings.

### ISSUE THREAD

**Issue by ddeimeke** [greymd/tmux-xpanes#119]
I installed tmux and tmux-xpanes from the corresponding GitHub-repositories and I get the following error message everytime I run xpane:

```
xpanes:Warning: 'xpanes' may not work correctly! Please check followings.
* tmux is installed correctly.
* Supported tmux version is installed.
  Version 1.8 and over is officially supported.
```

Here are the versions:

```
$ xpanes -V
xpanes 4.1.0-beta

$ tmux -V
tmux next-2.9
```

**Comment by greymd** [comment]
Hi @ddeimeke 
Thanks for using tmux-xpanes with latest version (Wow, 4.1.0-beta !).

This error message is displayed if the installed tmux verison is out of support.
But it seems that `xpanes` recognizes your tmux version incorrectly.
`xpanes` checks the result of `tmux -V` to check whether supported version of tmux is used or not.
But the latest tmux (on master branch) returns the irregular format like `next-2.9` and it causes the message.

I have no idea how to avoid the message functionally, because I cannot expect how tmux developers name the version number during their development in the future.
However, tmux-xpanes has the internal parameter to suppress the message.
Here is the workaround.

## Workaround

1. Install tmux-xpanes v4.1.0 ( [v4.1.0](https://github.com/greymd/tmux-xpanes/releases/tag/v4.1.0) just released by the way ).
2. Add this statement to your shell's `~/.*rc` file.

```
export TMUX_XPANES_TMUX_VERSION=2.9
```

The warning message will be gone.
Because `xpanes` recognizes tmux version as `2.9`.
This variable is not on the [README.md](github.com/greymd/tmux-xp…) because it's originally used for [testing purpose](https://github.com/greymd/tmux-xpanes/blob/master/test/cases_all.sh#L1491).

Thanks!

**Comment by ddeimeke** [comment]
Hi @greymd 

Thanks you for your quick answer.

It works perfectly well.

Thank you!

Cheers

Dirk
