### ISSUE TITLE
Fish shell compatibility

### ISSUE THREAD

**Issue by danielporto** [greymd/tmux-xpanes#128]
Any chance to see a fish shell compatible version coming out? 
it might be possible to hack by detecting fish and with the help of https://github.com/edc/bass to parse bash commands/variable expansions

**Comment by greymd** [comment]
Unfortunately, I do not have any motivations to make `xpanes` fish shell compatible.
In my understanding, `xpanes` can be used on the fish shell because it has the bash shebang as Bass says.

https://github.com/edc/bass
> Regular bash scripts can be used in fish shell just as scripts written in any language with proper shebang or explicitly using the interpreter (i.e. using bash script.sh). 

On the other hand, it says.

> However, many utilities, such as virtualenv, modify the shell environment and need to be sourced, and therefore cannot be used in fish. 

But I do not understand why `xpanes` need to be sourced in the fish shell.
Please let me know your use case :)
