### ISSUE TITLE
Specify argument number for substitution

### ISSUE THREAD

**Issue by dhorkin** [greymd/tmux-xpanes#139]
xpanes supports a -n argument, which lets you tell it you're going to be passing more than one argument per pane. Great! However... it doesn't appear like this does anything more than concatenate arguments.

Example:
`xpanes -n 2 -c "echo -e {} and {}" "a" "b" "c" "d"`
results in two panes with the following outputs: `a b and a b` and `c d and c d`

Given the `-n 2`, I would have assumed I'd get an output of `a and b` and `c and d`

I can use `-I` to change the `{}`, but it looks like multiple -Is are not allowed. So I can't go
`xpanes -n 2 -I{1} -I{2} -c "echo -e {1} and {2}" "a" "b" "c" "d"`

Additionally, trying to pass a bash array doesn't seem to work, either:
`xpanes -n 2 -c "echo -e {} and {}" ("a" "b") ("c" "d")`

I get: `zsh: number expected`

**Comment by greymd** [comment]
Hi,
Thank you for using tmux-xpanes deeply!

What you reported is current limitation of `-n` option.
Multiple placeholders (`{}`) are not bound to different arguments. 
Unfortunately, we do not have any plans to support separated placeholder like `{1}`, `{2}`...

Because I believe such the field separation procedure should be implemented in the user-defined script.
For example, I recommend you to use `-B` option with `alias`.
It seems that this is what you expected.

https://github.com/greymd/tmux-xpanes/wiki/Alias-examples#behaves-like-awk
> alias xpanes='xpanes -B "set {}"'
> $ xpanes -c 'echo $1-$2-$3' 'A B C' 'E F G' 'H I J' 'L M N'

**Comment by greymd** [comment]
If above workaround is not what you expected, please re-open this issue.
Thanks!
