### ISSUE TITLE
Why default to synchronize?

### ISSUE THREAD

**Issue by biocyberman** [greymd/tmux-xpanes#64]
If I run `xpanes {1..4}` all for window panes/splits are synchronize. With this, when I do `ls` for example, all panes do the same thing, giving the same output. Why would this be better default than turning synchronization of by default? I can make changes to the way I want, but just want to understand the rationale first.

**Comment by greymd** [comment]
The reason is that the old version of `tmux-xpanes` (which is [tmssh](https://github.com/greymd/tmssh)) was supposed to be used for connecting to multiple servers over SSH. I was sure that this behavior is more helpful than suppressing synchronization of panes, especially, if the user has many servers which have same configures.
For instance, similar script [tmux-cssh](https://github.com/dennishafemann/tmux-cssh) synchronizes all the panes by default.

If you do not like this behavior, use `-d` option or make alias of `xpanes` command with it.

```sh
alias xpanes="xpanes -d"
```

**Comment by biocyberman** [comment]
Making an alias is exactly what I did. Thanks
